.storybook/preview.tsx
panda.config.ts
src/app/[locale]/layout.tsx
src/fontLoader.ts
src/pages/_app.tsx

fix: add noto sans support for next.js and storybook 

---

panda.config.ts
src/components/uikit/Input/Input.stories.tsx
src/components/uikit/Input/Input.tsx
src/components/uikit/Input/index.ts
src/components/uikit/Textarea/Textarea.stories.tsx
src/components/uikit/Textarea/Textarea.tsx
src/components/uikit/Textarea/index.ts
src/components/uikit/index.ts

feat(KINGU-49): Input, Textarea components with corresponding stories

---

.projenrc.ts
.storybook/preview.tsx
package.json
panda.config.ts
postcss.config.cjs
src/components/uikit/Typography.stories.tsx

feat(KINGU-49): semantic typography, (temp) storybook hmr fix

---

panda.config.ts
src/components/uikit/Avatar/Avatar.recipe.ts
src/components/uikit/Input/Input.recipe.ts

move recipes from config to components folders

feat(KINGU-73): move panda recipes from config

---

panda.config.ts
src/components/uikit/Card/Card.stories.tsx
src/components/uikit/Card/Card.tsx
src/components/uikit/Card/index.ts

chore(KINGU-49): added transitions for card states

---

.storybook/main.ts

chore: added options for storybook mock module

---

src/components/Footer/Footer.tsx

fix(KINGU-96): fix links in footer

---

src/components/uikit/Avatar/Avatar.recipe.ts
src/components/uikit/PremiseCard/index.ts
src/components/uikit/Slider/index.ts
src/components/uikit/Tag/Tag.stories.tsx
src/components/uikit/Tag/Tag.tsx

Что сделал:
- Добавил вариант size для тегов;
- Изменил размеры аватаров;
- Добавил index.ts файлы для slider и premise card компонентов.

feat(KINGU-100): add size to tags and avatar

---

public/locales/en/common.json
public/locales/ru/common.json
src/components/Footer/Footer.recipe.tsx
src/components/Footer/Footer.tsx
src/components/Footer/LanguageDropdown.tsx
src/components/Header/Header.recipe.tsx
src/components/Header/Header.tsx
src/components/Header/HeaderLinks.tsx
src/components/headerOld/Header.tsx
src/components/headerOld/HeaderLinks.tsx
src/lib/utils/format-language.ts
src/lib/utils/index.ts
src/navigation.ts

- chore: moved language format feature to utils
- chore: style adjustments
Fixes #

feat(KINGU-103): responsiveness for footer/header

---

src/components/Footer/LanguageDropdown.tsx

fix: hydration fix

---

src/components/uikit/Accordion/Accordion.stories.tsx
src/components/uikit/Accordion/Accordion.tsx
src/components/uikit/Accordion/index.ts
src/components/uikit/Collapse/Collapse.tsx
src/components/uikit/index.ts

feat(KINGU-105): accordion component

---

prisma/migrations/20240503083224_add_price_cortege_premise_open_hours/migration.sql
prisma/schema.prisma
prisma/seed.ts
src/app/[locale]/premises/[slug]/page.tsx
src/components/premise/PremiseView.tsx
src/lib/actions/booking/premise-slots-intent.ts
src/lib/actions/premise/create-premise.ts
src/lib/utils/premise-time-slots/time-slots.ts

chore: removed usage of the `PremisePricing`

---

panda.config.ts
src/app/[locale]/auth/signin/loading.tsx
src/app/[locale]/premises/_filter-client-entry.tsx
src/components/Header/user-section.tsx
src/components/common/description/Description.tsx
src/components/common/maps/location-marker.tsx
src/components/uikit/Avatar/Avatar.tsx
src/components/uikit/Avatar/prepare-abbr.spec.ts
src/components/uikit/Avatar/prepare-abbr.ts
src/components/uikit/Modal/ModalWindow.tsx
src/components/uikit/PremiseCard/PremiseCard.tsx
src/components/uikit/Select/Select.recipe.ts
src/lib/actions/auth/update-user-profile.ts
src/theme/globalCss.ts

chore(KINGU-144): small ux adjustments

---

prisma/seed.prod.ts

chore: small production seed

---

public/locales/en/common.json
public/locales/pl/common.json
public/locales/ru/common.json
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/open-hours-selector.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/tabs/parameters-and-amenities.tsx
src/app/[locale]/profile/mybookings/page.tsx
src/components/calendar/BookingViewCard/BookingViewCard.tsx
src/components/common/checkout/CheckoutForm.tsx
src/components/profile/profile-navigation/profile-navigation.tsx
src/components/uikit/Accordion/Accordion.tsx
src/lib/actions/premise/edit-premise.ts

feat: added price and cancel button at the payment modal

---

src/lib/nextauth/providers.ts

fix: increase google oauth client timout for nextauth

---

src/components/common/form/InputSearchLocation/InputSearchLocation.tsx

chore: added default value for location search input

---

src/app/[locale]/auth/signin/user/sign-in-providers-form.tsx
src/app/[locale]/verify/verify-email.ts
src/lib/nextauth/callbacks.ts
src/server/adapters/auth-prisma.ts

chore: oauth fix and ux

---

public/locales/en/common.json
public/locales/pl/common.json
public/locales/ru/common.json
src/app/[locale]/profile/(company)/venues/_add-venue-form-tabs/contacts-group.tsx
src/app/[locale]/profile/(company)/venues/created/page.tsx
src/app/[locale]/profile/edit/@company/form-config.json
src/app/[locale]/profile/edit/@company/form.tsx
src/app/[locale]/profile/edit/@user/form-config.json
src/components/Header/user-section.tsx
src/components/brand/contacts.tsx
src/components/common/go-back-button.tsx
src/components/premise/PremiseView.tsx
src/components/profile/profile-navigation/profile-navigation.tsx
src/components/uikit/Avatar/Avatar.recipe.ts
src/components/uikit/Forms/BaseForm.tsx
src/components/uikit/Forms/Elements/FormField.tsx
src/components/uikit/Forms/Elements/SocialLinks.tsx
src/lib/actions/premise/tabs/mainInformation.ts
src/lib/actions/venue/create-venue.ts
src/lib/actions/venue/validation.ts
src/lib/shared/config/premise-types.ts
src/lib/validations/auth/org-register.ts
src/lib/validations/auth/user-profile.ts

fix(KINGU-147): qa changes

---

src/components/calendar/WeekView/MonthSelect.tsx

fix: fixed month selector

---

src/app/[locale]/premises/[slug]/page.tsx
src/app/[locale]/profile/(company)/venues/created/page.tsx
src/components/common/form/ProfileImagePicker/ProfileImagePicker.tsx
src/components/premise/PremiseView.tsx

chore(KINGU-150): link follow to a new tab; hiding meta in the image picker

---

src/app/[locale]/_ga.tsx
src/app/[locale]/layout.tsx

feat: ga [init]

---

consumer/processors/premise-fulfilled/upsert-premise-fulfilled-index.ts
prisma/migrations/20240812170857_add_localized_info_premise_and_venue/migration.sql
prisma/schema.prisma
src/app/[locale]/premises/[slug]/page.tsx
src/app/[locale]/profile/(company)/venues/[id]/[premiseId]/form.tsx
src/app/[locale]/profile/(company)/venues/[id]/[premiseId]/page.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/tabs/main-information.tsx
src/app/[locale]/profile/(company)/venues/[id]/form.tsx
src/app/[locale]/profile/(company)/venues/[id]/page.tsx
src/app/[locale]/profile/(company)/venues/_add-venue-form-tabs/main-info.tsx
src/app/[locale]/venues/[slug]/page.tsx
src/components/premise/PremiseView.tsx
src/lib/actions/premise/create-premise.ts
src/lib/actions/premise/edit-premise.ts
src/lib/actions/premise/tabs/mainInformation.ts
src/lib/actions/venue/create-venue.ts
src/lib/actions/venue/edit-venue.ts
src/lib/actions/venue/validation.ts

feat: split descriptions filling by locales

---

.helm/values.yaml

Fixes #
increase consumer limits and requests

fix: increase consumer limits and requests

---

emails/booking-email.tsx
prisma/migrations/20240827124037_add_premise_donation_base/migration.sql
prisma/schema.prisma
public/locales/en/common.json
public/locales/pl/common.json
src/app/[locale]/premises/[slug]/page.tsx
src/app/[locale]/profile/(company)/venues/[id]/[premiseId]/form.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/add-open-hours-record.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/open-hours-selector.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/tabs/open-hours-and-prices.tsx
src/app/[locale]/profile/(company)/venues/[id]/add-premise/form.tsx
src/app/api/webhook/route.ts
src/components/calendar/BookingViewCard/BookingViewCard.tsx
src/components/calendar/BookingViewCard/PriceBlock.tsx
src/components/calendar/BookingViewContext.tsx
src/components/calendar/WeekView/WeekView.tsx
src/components/common/checkout/CheckoutForm.tsx
src/components/uikit/PremiseMyBookingCard/BookingsSection.tsx
src/components/uikit/TimeSlot/TimeSlot.tsx
src/lib/actions/booking/premise-slots-intent.ts
src/lib/actions/premise/tabs/openHoursAndPrices.ts
src/lib/shared/config/donation.ts
src/lib/shared/stripe/index.ts

feat: donation price mode for premises

---

public/locales/en/common.json
public/locales/pl/common.json
src/app/[locale]/error.tsx
src/components/common/go-back-button.tsx

feat: added error page

---

src/app/[locale]/premises/_filter.tsx
src/components/filters/filter-element.tsx
src/lib/actions/premise-filter/resolvers/simple-keys.ts
src/lib/shared/config/amenities.ts

feat: aggregations group tags

---

src/lib/actions/premise-filter/resolvers/simple-keys.ts

feat: show `Else` type halls always

---

panda.config.ts
prisma/migrations/20240930115228_add_min_slots_to_book/migration.sql
prisma/schema.prisma
public/locales/en/common.json
public/locales/pl/common.json
src/app/[locale]/premises/[slug]/page.tsx
src/app/[locale]/profile/(company)/venues/[id]/[premiseId]/form.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/tabs/open-hours-and-prices.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/tabs/options-selector.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/tabs/price-mode-selector.tsx
src/components/calendar/BookingViewCard/BookingViewCard.tsx
src/components/calendar/WeekView/WeekView.tsx
src/lib/actions/booking/premise-slots-intent.ts
src/lib/actions/premise/tabs/openHoursAndPrices.ts

feat: added min edge of slots to book

---

src/app/[locale]/premises/[slug]/page.tsx
src/components/premise/PremiseAmenities.tsx
src/lib/shared/config/amenities.ts

feat: grouped amenities at the premise page

---

src/app/[locale]/layout.tsx
src/components/analytics/consent.tsx
src/components/analytics/index.ts
src/components/analytics/meta-pixel.tsx

chore: added meta pixel

---

src/app/[locale]/premises/[type]/page.tsx

chore: removed static params generation

---

src/components/uikit/Avatar/prepare-abbr.ts

chore: replaced `positive lookbehind` to be working on older browsers

---

consumer/processors/premise-fulfilled/prepare-closed-hours.spec.ts
consumer/processors/premise-fulfilled/prepare-closed-hours.ts
src/components/common/cards/time-range/time-range-link.tsx
src/lib/actions/premise-filter/resolvers/search-datetime.ts

fix: fixed cases for `24/7` and `00:00/24:00` as the border

---

consumer/processors/premise-fulfilled/prepare-closed-hours.spec.ts
consumer/processors/premise-fulfilled/prepare-closed-hours.ts
package-lock.json
src/app/[locale]/blog/_widgets/blog-main-interaction.tsx
src/app/[locale]/blog/_widgets/blog-main.tsx
src/components/common/cards/time-range/time-range-link.tsx
src/lib/actions/premise-filter/resolvers/search-datetime.ts

fix: blog inital has-more pagination bug

---

package-lock.json
src/app/[locale]/b2b/_widgets/blog-link-card.tsx
src/app/[locale]/blog/[slug]/page.tsx
src/app/[locale]/blog/_widgets/blog-card.tsx
src/app/[locale]/blog/_widgets/blog-main-interaction.tsx
src/app/[locale]/blog/_widgets/innerPage/inner-blog-header.tsx
src/app/[locale]/blog/_widgets/innerPage/inner-blog-main.tsx
src/app/[locale]/blog/interfaces.ts
src/lib/utils/format-date.ts
src/lib/utils/format-text.ts

fix: second try to fix bug in blogs which related to 422 425 errors

---

src/app/[locale]/blog/_widgets/blog-main-interaction.tsx

fix: the truncate text issue

---

src/app/[locale]/blog/_widgets/blog-main.tsx
src/app/[locale]/blog/page.tsx

fix: 422 425 error in react app

---

src/components/calendar/BookingViewCard/BookingViewCard.tsx
src/components/error-handling/gateway.tsx
src/lib/actions/event/order/ticketIntent.ts

fix: chunk error catcher

---

prisma/migrations/20250221231821_feat_to_user_2_field_related_to_transaction_counting/migration.sql
prisma/migrations/20250222182434_removed/migration.sql
prisma/schema.prisma
public/locales/en/common.json
public/locales/pl/common.json
src/app/[locale]/premise/[slug]/page.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/tabs/rules.tsx
src/components/calendar/BookingViewCard/BookingViewCard.tsx
src/components/calendar/BookingViewCard/PriceBlock.tsx
src/components/calendar/WeekView/WeekView.tsx
src/components/common/checkout/CheckoutForm.tsx
src/components/error-handling/gateway.tsx
src/components/premise/PremiseView.tsx
src/components/premise/get-premise-view-data.ts
src/components/premise/premise-view-card.tsx
src/components/uikit/TimeSlot/TimeSlot.tsx
src/lib/actions/booking/get-user-by-id.ts
src/lib/actions/booking/premise-slots-intent.ts
src/lib/actions/booking/update-transaction-count.ts
src/lib/actions/index.ts
src/lib/actions/tax/format-price-with-tax.ts
src/lib/actions/tax/index.ts
src/lib/shared/constants.ts
src/lib/utils/format-price.ts
src/lib/utils/price/discounts.ts

feat: tax logic to all system with new field to user and validation

---

src/components/uikit/TimeSlot/TimeSlot.tsx
src/lib/actions/booking/premise-slots-intent.ts

fix: build error

---

src/components/calendar/BookingViewCard/BookingViewCard.tsx
src/components/calendar/WeekView/WeekView.tsx
src/lib/actions/tax/format-price-with-tax.ts

fix: logic which related to tax

---

public/locales/pl/common.json
src/app/[locale]/b2b/page.tsx
src/app/[locale]/profile/(company)/venues/[id]/_premise-form/open-hours-selector.tsx
src/components/analytics/meta-pixel.tsx
src/components/analytics/ym-scripts.tsx
src/lib/actions/premise/create-premise.ts
src/lib/actions/premise/edit-premise.ts
src/lib/actions/premise/tabs/openHoursAndPrices.ts
src/lib/actions/premise/validation.ts

fix: b2b-changes/vendor donation mode

---

src/app/[locale]/premise/[slug]/page.tsx
src/components/calendar/BookingViewCard/BookingViewCard.tsx
src/lib/actions/booking/premise-slots-intent.ts
src/lib/actions/event/order/ticketIntent.ts
src/lib/actions/tax/format-price-with-tax.ts
src/lib/shared/stripe/index.ts

feat: stripe changes and modified logic for untaxes

---

src/app/[locale]/premise/[slug]/page.tsx
src/app/[locale]/profile/edit/@company/page.tsx
src/app/[locale]/profile/edit/@user/page.tsx
src/lib/actions/booking/premise-slots-intent.ts

feat: redirect when user don't have the session in premise detail

---

src/app/[locale]/profile/(company)/venues/[id]/form.tsx
src/app/[locale]/profile/(company)/venues/_add-venue-form-tabs/main-info.tsx
src/app/[locale]/profile/(company)/venues/add/form.tsx
src/lib/actions/venue/edit-venue.ts

fix: previous logic which related to field name in edit venue

---

src/app/[locale]/premise/[slug]/page.tsx

fix: rewrited logic in premise detail wtihout session

---

src/app/[locale]/premise/[slug]/page.tsx

fix: extra import

---

src/components/premise/premise-view-card.tsx

fix: rewrited map component into client

---

public/locales/pl/common.json

feat: translated all json into the polish

---

src/app/[locale]/premises/_widgets/listing.tsx
src/lib/actions/premise-filter/listing.ts

fix: elastic search sync with backend data

---

src/app/[locale]/premises/_widgets/listing.tsx
src/lib/actions/premise-filter/listing.ts

Reverts kinguru-io/kinguru-next#1007

Revert "fix: elastic search sync with backend data"
